version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      k8s:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      rancher:
        patterns:
          - "github.com/rancher/*"
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      golang-x:
        patterns:
          - "golang.org/x/*"

  - package-ecosystem: "terraform"
    directory: "/terraform/digitalocean"
    schedule:
      interval: "weekly"
